spring.application.name=sonriapp
spring.datasource.url=jdbc:mysql://localhost:3306/sonriapp
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=dev
reniec.api.url=https://api.apis.net.pe/v2/reniec/dni?numero=
reniec.api.token=Bearer apis-token-16031.5qKEr2NSEEHNUwXl3C9KiEYret6W9Tte

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sercoyt.eirl@gmail.com
spring.mail.password=ztubepiniokgsvxz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

app.base-url=http://localhost:8080



