spring.application.name=sonriapp
spring.datasource.url=jdbc:mysql://localhost:3306/sonriapp
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=dev
